services:
  db:
    container_name: photo_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: photo_go
    ports:
      - "5422:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - photo_net
volumes:
  pgdata:
networks:
  photo_net:
    driver: bridge
